name: ✏️Review By ChatGPT

on:
    pull_request:
        types: [opened, reopened, synchronize]

permissions:
    contents: read
    pull-requests: write

jobs:
    review:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: Run ReviewGPT
              uses: anc95/ChatGPT-CodeReview@main
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
                  MODEL: gpt-4o
